name: Generate CLI commands doc page

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]

env:
  PLATFORMSH_CLI_NO_INTERACTION: 1
  PLATFORM_PROJECT: ucq44jg6ofare
  PLATFORMSH_CLI_DEFAULT_TIMEOUT: 60 # Increase timeout for CLI commands
  SLEEP_TIME: 5
  NUM_TRIES: 30
  BRANCH_TITLE: test-${{ github.event.number }}

jobs:
  build:
    #if: github.event.label.name == 'build-fork' || contains(github.event.pull_request.labels.*.name, 'build-fork')
    #runs-on: ubuntu-latest
    steps:
#      - uses: actions/checkout@v3
#        with:
#          ref: ${{ github.event.pull_request.head.sha }}
#          token: ${{ secrets.WORKFLOW_TOKEN }}

      # Set up workflow environment to use the Platform.sh CLI
      - name: Set up Platform.sh CLI
        uses: ./.github/actions/set-up-cli

      # Generate CLI command doc pages
      - env:
          PLATFORMSH_CLI_TOKEN: 5QBxYXD32M8dvSlICymsY82wsiPU-5gc_R09mYj0FZI
          # @see activate_environment:Set environment title:env in manage-environment.yaml
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: |
          # Get most recent changes
          git checkout ${{ github.event.pull_request.head.sha }}

          # Put most recent changes on the branch
          echo "Switching to branch ${{ env.BRANCH_TITLE }}"
          git switch -C ${{ env.BRANCH_TITLE }}

          echo "Pushing most recent changes"
          git push --force origin ${{ env.BRANCH_TITLE }}

          platform list --format=md > platform-commands.html
          git add platform-commands.html
          git commit -m "generating Platform CLI command doc page"
          git push --force origin ${{ env.BRANCH_TITLE }}
