name: Generate CLI commands doc page

on:
  workflow_dispatch:
    branches: [ main, test-workflow ]
#  pull_request:
#    branches: [main]
#    types: [labeled,opened,unlabeled,synchronize]
#  schedule:
#    # Run at 00:15 every day
#    - cron: '15 */19 * * *'

env:
  PLATFORMSH_CLI_NO_INTERACTION: 1
  PLATFORM_PROJECT: ${{ vars.PROJECT_ID }}
  PLATFORMSH_CLI_DEFAULT_TIMEOUT: 60 # Increase timeout for CLI commands
  SLEEP_TIME: 5
  NUM_TRIES: 30
  BRANCH_TITLE: ${{ vars.BFF_PREFIX }}-cli-command-doc-page
  DEFAULT_BRANCH: "main"
  PLATFORMSH_CLI_DOC_PATH: "sites/platform/src/administration/cli/reference.html"
  UPSUN_CLI_DOC_PATH: "sites/friday/src/administration/cli/reference.html"
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Get Default Branch
#      - uses: actions/checkout@v3
#        with:
#          ref: $DEFAULT_BRANCH
#          token: ${{ secrets.WORKFLOW_TOKEN }}
#
#      # Set up workflow environment to use the Platform.sh CLI
#      - name: Set up Platform.sh CLI
#        uses: ./.github/actions/set-up-cli
#
#      # Set up workflow environment to use the Upsun CLI
#      - name: Set up Upsun CLI
#        uses: ./.github/actions/set-up-upsun-cli
#
#      # Set Platform.sh CLI doc page CHECKSUM
#      - name: Set CHECKSUM for
#        run: echo PSH_CHECKSUM=$(shasum -a 1 ${{ env.PLATFORMSH_CLI_DOC_PATH }} | awk '{ print $1 }') >> $PSH_CHECKSUM
#
#      # Generate Platform.sh CLI command doc pages
#      - env:
#          #PLATFORMSH_CLI_TOKEN: ${{ secrets.PLATFORMSH_CLI_TOKEN }}
#          #UPSUN_CLI_TOKEN: ${{ secrets.PLATFORMSH_CLI_TOKEN }}
#          # @see activate_environment:Set environment title:env in manage-environment.yaml
#          PR_TITLE: ${{ github.event.pull_request.title }}
#        run: |
#          # Generate Platform.sh CLI command doc pages
#
#          # Set current user
#          #git config --global user.name 'CLI Command doc page auto generator'
#          #git config --global user.email 'flovntp@gmail.com'
#
#          # Get most recent changes from main
#          git checkout $DEFAULT_BRANCH
#
#          # Put most recent changes on the branch
#          echo "Switching to branch ${{ env.BRANCH_TITLE }}"
#          git switch -C ${{ env.BRANCH_TITLE }}
#
#          # Adding CLI Commands specific page
#          echo "Generating Platform.sh CLI doc page"
#          ./shared/scripts/gen-cli-docs.sh
#          git add ${{ env.PLATFORMSH_CLI_DOC_PATH }}
#          git commit -m "generating Platform CLI command doc page"
#
#          echo "Pushing most recent changes"
#          git push --force origin ${{ env.BRANCH_TITLE }}
#
#          #gh pr view ${{ env.BRANCH_TITLE }}
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.DEFAULT_BRANCH }}
          token: ${{ secrets.WORKFLOW_TOKEN }}

      - name: Make changes to pull request
        run: date +%s > report.txt

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
          commit-message: Update on
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: ${{ env.BRANCH_TITLE }}
          delete-branch: false
          title: '[Example] Update report'
          body: |
            Update report
            - Updated with *today's* date
            - Auto-generated by [create-pull-request][1]
            
            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            report
            automated pr
          assignees: flovntp
          reviewers: flovntp
          milestone: 1
          draft: false
